type MemberEmail ={
    name: string;
    email: string;
}

const MemberEmails: MemberEmail[] = [
  { name: '해시', email: 'mtsealove@geekble.kr' },
  { name: '룬롱', email: 'runrong@geekble.kr' },
  { name: '로빈', email: 'mkro@geekble.kr' },
  { name: '라니', email: 'rani@geekble.kr' },
  { name: '토니', email: 'tonyhdkim@geekble.kr' },
  { name: '밍', email: 'ming@geekble.kr' },
  { name: '다이오드', email: 'die0d@geekble.kr' },
  { name: '스톤', email: 'stone@geekble.kr' },
  { name: '태태', email: 'jeongtae@geekble.kr' },
  { name: '민바크', email: 'sherlotics92@geekble.kr' },
  { name: '여름', email: 'eb.kim@geekble.kr' },
  { name: '하이', email: 'seoha@geekble.kr' },
  { name: '잔잔', email: 'zhanzhan@geekble.kr' },
  { name: '티노', email: '0eun@geekble.kr' },
  { name: '새벽', email: 'dawn@geekble.kr' },
  { name: '주철', email: 'joo@geekble.kr' },
  { name: '해리', email: 'yeah@geekble.kr' },
  { name: '람람', email: 'boram@geekble.kr' },
  { name: '찬스', email: 'chance@geekble.kr' },
  { name: '팡', email: 'sy@geekble.kr' },
  { name: '갈퀴', email: 'leeminsuk@geekble.kr' },
  { name: '잭키', email: 'jack2248@geekble.kr' },
  { name: '시안', email: 'cyanmaker@geekble.kr' },
  { name: '우기', email: 'ktw@geekble.kr' },
  { name: '수드래곤', email: 'soodragon@geekble.kr' },
  { name: '키쿠', email: 'kiku@geekble.kr' },
  { name: '카프', email: 'cmonincoff@geekble.kr' },
  { name: '숨숨', email: 'sumsum@geekble.kr' },
  { name: '모루', email: '9insu@geekble.kr' },
  { name: '고호', email: 'looxi88@geekble.kr' },
  { name: '홀리볼리', email: 'hollybolly@geekble.kr' },
  { name: '나모', email: 'namo@geekble.kr' },
  { name: '귀비', email: 'younggenius@geekble.kr' },
  { name: '해수', email: 'seongmin@geekble.kr' },
  { name: '빽곰', email: 'backkom@geekble.kr' },
  { name: '소', email: 'so@geekble.kr' },
  { name: '마크', email: 'mkim@geekble.kr' },
  { name: '민주스', email: 'minjuice@geekble.kr' },
  { name: '한나', email: 'hanna.park@geekble.kr' },
  { name: '키니', email: 'kiny@geekble.kr' },
  { name: '투넬', email: 'tunel@geekble.kr' },
  { name: '지니', email: 'ljin@geekble.kr' },
];

export default MemberEmails;
